sudo: false
language: python
python: "3.6"
addons:
  firefox: "56.0.1"
before_install:
  - "export DISPLAY=:99.0"
  - "./geckodriver-install.sh"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install -g selenium-standalone"
  - "selenium-standalone install"
  - "selenium-standalone start &"
env:
  matrix:
    - TESTENV=linters
    - TESTENV=py27
    - TESTENV=py27-xdist
    - TESTENV=py27-pytest-latest
    - TESTENV=py36
    - TESTENV=coveralls
install:
  - pip install tox
script: tox -e $TESTENV
branches:
  except:
    - /^\d/
notifications:
  email:
  - bubenkoff@gmail.com
